/**
 * Reads the static snapshot generated by `npm run sync` (see docs/adr/0001-data-source.md).
 */
import type { LaunchDetail, LaunchSummary, Rocket, SnapshotMeta } from "@/types/domain";
import { fetchJson } from "./http";

const BASE = `${import.meta.env.BASE_URL}data`;

export const getLaunches = () => fetchJson<LaunchSummary[]>(`${BASE}/launches.json`);

export const getLaunch = (slug: string) =>
  fetchJson<LaunchDetail>(`${BASE}/launches/${encodeURIComponent(slug)}.json`);

export const getRockets = () => fetchJson<Rocket[]>(`${BASE}/rockets.json`);

export const getMeta = () => fetchJson<SnapshotMeta>(`${BASE}/meta.json`);
